services:
  # FastAPI Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rental-rag-backend
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s
    networks:
      - rental-rag-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Streamlit Frontend Service  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rental-rag-frontend
    restart: unless-stopped
    environment:
      - FASTAPI_URL=http://backend:8000/query
      - DEMO_PASSWORD=${DEMO_PASSWORD}
      - API_SECRET_KEY=${API_SECRET_KEY}
    depends_on:
      - backend
    networks:
      - rental-rag-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  rental-rag-network:
    driver: bridge